# 1. create the stack 
# 2. update the stack with env_type=prod
# 3. create a second stack (env_type=test)
# 4. lister stack (lab1 et lab1.test )
# 5. show event list stack de prod

heat_template_version: 2014-10-16
description: Lab 1 - Params, Params Group
parameters:
  username:
    type: string
    constraints:
     - length: { min: 6, max: 8 }
       description: User name must be between 6 and 8 characters
     - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
       description: User name must start with an uppercase character
  password:
    type: string
    hidden: true
  env_type:
    default: test
    type: string
    constraints:
      - allowed_values: [prod, test]

parameter_groups:
- label: user-auth
  description: User Authentication
  parameters:
  - username
  - password
