heat_template_version: 2016-10-14
# openstack stack create --wait -f yaml -t lab3.yml --parameter "username=Testing1" --parameter "password=Toto0000" --parameter "image=CirrOS 0.4.0" --parameter "key_name=oswald" lab3
description: Lab 1,2 - Params, Params Group, Resource Section
parameters:
  username:
    type: string
    constraints:
     - length: { min: 6, max: 8 }
       description: User name must be between 6 and 8 characters
     - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
       description: User name must start with an uppercase character
  password:
    type: string
    hidden: true
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
  env_type:
    default: test
    type: string
    constraints:
      - allowed_values: [prod, test]
  public_net:
    type: string
    description: Network ID to use
    default: net-2061-ext-ssh
    constraints:
      - custom_constraint: neutron.network
  ports:
    type: comma_delimited_list
    default: "80,443"

parameter_groups:
- label: user-auth
  description: User Authentication
  parameters:
  - username
  - password
- label: other
  description: Environment & Network
  parameters:
  - env_type
  - public_net
  - key_name
  - image
  - flavor

conditions:
  create_prod_res: {equals : [{get_param: env_type}, "prod"]}

resources:
  private_net:
    type: OS::Neutron::Net

  #3
  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: "10.8.1.0/24"
      dns_nameservers: [ "8.8.8.8", "8.8.4.4" ]
      ip_version: 4

  #3
  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  #3
  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  #3
  web_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        #4
        repeat:
          template:
            protocol: tcp
            port_range_min: <%port%>
            port_range_max: <%port%>
          for_each:
            <%port%>: { get_param: ports }

  #3
  my_key:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: my_key

  server1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_net }
      security_groups:
        - default
        - { get_resource: web_secgroup }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server1_port }

  server1:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
      - port: { get_resource: server1_port }
    depends_on: server2

  server2:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
      - network: { get_param: public_net }

  volume:
    type: OS::Cinder::Volume
    condition: create_prod_res
    properties:
      size: 1

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    condition: create_prod_res
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: server1 }

outputs:
  server1_private_ip:
    description: IP address of server1 in private network
    value: { get_attr: [ server1, first_address ] }

  server1_public_ip:
    description: Floating IP address of server1 in public network
    value: { get_attr: [ server1_floating_ip, floating_ip_address ] }

  server2_private_ip:
    description: IP address of server2 in private network
    value: { get_attr: [ server2, first_address ] }

  private_key:
    description: Private key
    value: { get_attr: [ my_key, private_key ] }
